### ISSUE TITLE
constructed file name not matching database

### ISSUE THREAD

**Issue by dgorthi** [vihangmehta/extract_BC03#1]
The filename of the .ised file that being constructed by the wrapper is 'bc2003_lr_m62_chab_ssp' while the database has them called 'bc2003_lr_BaSeL_m62_chab_ssp'.

**Comment by vihangmehta** [comment]
The code was initially setup to run on the older version of GALAXEV. The "updated 2012" version of the code has a few differences -- not only in the library file and filenames, but also in the source code itself. I have added a keyword arg "library_version" for the TemplateSED_BC03() class to accommodate the new 2012 version of GALAXEV.

To use extract_BC03 with the new 2012 version of GALAXEV, use the keyword argument "library_version=2012" when setting up the TemplateSED_BC03() class along with the "library" keyword to specify which library of models to use "BaSeL" or "stelib".

Also added a functionality to directly specify an ISED filename. Use keyword "input_ised" to specify a particular ISED file.
